### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by mottosso** [richardlayman/feather#13]
My development platform is Windows so I was having a look at getting Feather to build on it and here are some of the issues I encountered thus far.

1. The `gcc` flags `-ggdb` and `-fPIC` don't get recognised by Visual Studio
2. dlfcn is POSIX-only (but there is [a port](https://github.com/dlfcn-win32/dlfcn-win32)).
3. Qt binaries aren't provided for Visual Studio 2015, which I think we need for C++11 support
4. Hardcoded paths in CMakeLists.txt (e.g. `/usr/local`) prevent install

I haven't managed to build it yet, but getting close. I'll update this list as I go, and hopefully by the time this issue is closed Feather will be running on Windows.

Some questions.

(2) Can Feather run without dlfcn? Is there an alternative that is cross-platform?
(4) can we make these relative to CMAKE_INSTALL_PREFIX? Looks like it defaults to `/usr/local` anyway, which on Windows defaults to an equivalent (`c:\program files`).

**Comment by richardlayman** [comment]
I don't have any Windows machines anymore and not a big fan of them; I run Linux all the time now - even at work. But I do have a do Windows builds for our company software every now-and-then so I know Feather should build on Windows even though I've never built it on Windows yet; Feather uses all the same libraries I use in my other software that is built for Windows. I use MinGW for when I have to build on Windows, not a big fan of VS. But I have to say this now, one thing I'm very much against is having Window specific code or functions in the main source unless it's part of the build or wrapped with a define. My main target is Linux with Windows support, not the other way around. In fact, I wasn't even going to provide a Windows build myself; I was going to leave it to someone else that was willing to support it. It's hard for me to fix Windows bugs when I don't even have a Windows box. No Windows code will be merged into the mainline that breaks the Linux build, provides functionality to Windows that not available on Linux, or mixes Window specific code into the source. I and Windows IDE's are used, none of their project files must creep into the main source; it has to be in a separate folder away from the source.

Hope I'm not coming off as a Linux snob or being an ass, I'm just trying to explain my position on this matter as best I can.

>(2) Can Feather run without dlfcn? Is there an alternative that is cross-platform?

We can wrap it in a define. CMake already passes Linux, Win32, MacOS flags to the compiler.

>(4) can we make these relative to CMAKE_INSTALL_PREFIX? Looks like it defaults to /usr/local anyway, which on Windows defaults to an equivalent (c:\program files).

Add a define just like above; that will take care of it.

**Comment by richardlayman** [comment]
Here are some notes I wrote on doing Windows builds. It's for Qt4 but lots of the stuff is still relevant.
The formatting is a little messed up because I copy-n-pasted it but you get the point.

...



Before you start this tutorial, you want to make sure that you have MinGW 4.6, or lower, installed (NOT 4.7 or greater) along with QtSDK 4.8 (this is compiled for 4.4 but will work up to 4.6). You want to compile all your software with the qtsdk version, but it still uses the mingw installation eventhough it has it's own. If anyone of your dlls are compiled with 4.7, your application would crash as soon as it tried to load it - this includes the qt dlls.

Also, it's important to note that dlls compiled by other programs, such as Visual Studio, will not work with applications compiled with MinGW.
 
What you need to do is use CMake with MinGw. So you need to install CMake, MinGW, and the Qt SDK onto your Windows machine. In CMake you can get the OS your on by using this:

# SETUP THE OS

# CMAKE_SYSTEM_NAME while output Linux, Windows, and Darwin (Mac OSX)
# OS
# LINUX
IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    # Linux specific code
    SET(OperatingSystem "Linux")
    add_definitions(-DLINUX)

    # Processor
    IF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")
        # Intel Linux Specific Code
        SET(Processor "Intel")
    ENDIF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")

ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")

# MAC 
IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    # Mac OS X specific code
    SET(OperatingSystem "Mac OS X")
    add_definitions(-DMAC_OSX)


    # Processor
    IF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")
        # Intel Mac OS X Specific Code
        SET(Processor "Intel")
    ENDIF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")

ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

# WIN32 
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    # Mac OS X specific code
    SET(OperatingSystem "Windows")
    add_definitions(-DWINDOWS)

    # This will get rid of that annoying console window that pops up on startup
    set(CMAKE_CXX_LINK_FLAGS ${CMAKE_CXX_LINK_FLAGS} "-Wl,-subsystem,windows")
    # Processor
    IF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")
        # Intel Windows Specific Code
        SET(Processor "Intel")
    ENDIF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Intel")

ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")



You can then put OS specific stuff into your code using this:


#ifdef LINUX
std::cout << "Linux OS\n";
#endif

#ifdef MAC_OSX
std::cout << "Mac OS\n";
#endif

#ifdef WINDOWS
std::cout << "Window OS\n";
#endif

Once you've fixed all the OS specific code, you can generate MinGw Makefiles using this (You are doing this in Windows from the shell)
>CMake -Wno-dev -G"MinGW Makefiles" 

Now you just build it like normal
>C:\QtSDK\MinGW\bin\mingw-make.exe

Now you'll probably have some issues building it because it will say that it can't find Qt or MinGW. To fix this problem you will open Start>Settings>ControlPanel>System>Advanced>Environment Variables>System variables>[select PATH]>Edit
You might need to change the order of the paths since windows tries to use the first one that matches - for example, mine kept failing because it was trying to use my Python Qt dlls instead of the SDK ones because it's path was before the SDK's.

To run the program I found that it's easiest just to copy all the dlls, that CMake built, to the same folder that you running the program so that it can find it.

To package the software, I just copied QtGui4.dll, QtCore4.dll, mingwm10.dll, listed++-6.dll, libgcc_s_dw2-1.dll, libquadmath-0.dll in the same folder also [these may change depending on what your program uses] - that makes it possible for the end user to run the program without having to install any of these programs. download dependencywalker to find out all the dlls that your program uses.


RUNNING WITH GDB

I have not been able to get gdb to work on Windows yet and I think this is because the Virus protection is stopping it from working, but I'm not sure on that one. I do know that you will get errors trying to load the program with gdb if you have it in a folder with spaces in the name. The only way around this is to make a folder in C:\ with a non-spaced name and put your project in there.

You can run msconfig.exe to disable services. I had heard that this problem could be solved by disabling HsMgr but I don't have that on my computer.

**Comment by mottosso** [comment]
> Hope I'm not coming off as a Linux snob or being an ass, I'm just trying to explain my position on this matter as best I can.

Not at all. It sounds to me that what you're saying is that you want Feather to be cross-platform, and that's what I want too.

> I was going to leave it to someone else that was willing to support it.

You've got your man right here.

> We can wrap it in a define. CMake already passes Linux, Win32, MacOS flags to the compiler.

This is currently over my head, but with some pointers I'd be happy to try and resolve this.

**Comment by richardlayman** [comment]
>This is currently over my head, but with some pointers I'd be happy to try and resolve this.

CMake already knows what platform it's building on without you having to tell it. You can grab these defines in the CMake or also use them in the source file. An example of this would be if you wanted to install the exe in a different location. But  first you need to put the CMake setup code (what I posted above) in the root CMakeList.txt which will setup the flags to be passed to the source. You can then setup various parts of the CMake using the below code.

    IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        INSTALL(TARGETS feather RUNTIME DESTINATION C:\programs)
    ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        INSTALL(TARGETS feather RUNTIME DESTINATION /usr/local)
    ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")

You can use this anywhere in any CMake file for platform specific tasks. You can catch the platform flags in the source as well.

    #ifdef LINUX
    // run Linux function
    #endif

    #ifdef WINDOWS
    // run Windows function
    #endif  

You can make your own flags and catch them using

    IF(MYFLAG)
        ....
    ELSE(MYFLAG)
        ....
    ENDIF(MYFLAG)

You would activate MYFLAG by using.

    cmake -DMYFLAG ..

**Comment by mottosso** [comment]
Thanks Richard, I'm not terribly familiar with C++ but I'll have a look to see if there's anything I can do about this. I am in the process of picking it up.

My first thought would be that the library you use, dlfcn, is something you use for plug-ins? In that case it sounds like we'll need to either find an equivalent for Windows, or find an alternative that works cross-platform. Which do you think is better for our use case? Perhaps it's as simple as merely loading the binary using the native functionality of each OS?

About plug-in architectures in C++, I've only got experience doing this in Python. What are your thoughts on what is described here?

- http://sourcey.com/building-a-simple-cpp-cross-platform-plugin-system/

> I don't have any Windows machines anymore and not a big fan of them; I run Linux all the time now - even at work.

Just to make sure I'm not misreading you, you do want to support users running the Windows platform? I would guess most end users out there will be on Windows, after all. Unless you target an audience other than the general public, perhaps a specialist market? Let me know if this is the case as it changes a few things.

**Comment by richardlayman** [comment]
>My first thought would be that the library you use, dlfcn, is something you use for plug-ins? In that case it sounds like we'll need to either find an equivalent for Windows, or find an alternative that works cross-platform.

dlfcn is for loading the linux so library files, dll's are the Window's equivalent and can be loaded using LoadLibrary().
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx
It has to be done this way due to how the different OS's work; you have to use these functions to load libraries at runtime. Cpp can't be loaded through a library due to name mangling so it's exported to a C interface and then this is used to call the functions inside the library. This holds true across all platforms.

>Perhaps it's as simple as merely loading the binary using the native functionality of each OS?

dlfcn is the native Linux library loader.

>Just to make sure I'm not misreading you, you do want to support users running the Windows platform? I would guess most end users out there will be on Windows, after all. Unless you target an audience other than the general public, perhaps a specialist market? Let me know if this is the case as it changes a few things.

My original thought was to only develop Feather for Linux and I figured, after a few versions, I would have a small group of core Linux developers helping me. I didn't expect any interest from the Windows group until it reached a higher level of functionality (v1.0-v2.0). At that time I thought Feather would be big enough to where a Windows group could sustain themselves without any help from me. I couldn't work on the Windows version because, since I don't have access to a Windows box, I can't verify none of the issues or see if the fix worked. I don't mind posting Windows binaries on the site and they would be allowed to post bugs, but I just wouldn't be working on them.

The target for Feather was indie's or very small studio's. I wouldn't expect any interest from larger studios till much later, if ever. One of Feather's key selling points is that you can take it apart and reassemble it to do certain tasks - in effect making into around how you work (much like Maya). This makes it good for people that use pipelines and need solutions to specific problems but not very useful for general users. Also, in future, Feather will have terminal commands making it possible to use Feather in Bash which I've been wanting for a long time.
