### ISSUE TITLE
Contribution Instructions

### ISSUE THREAD

**Issue by mottosso** [richardlayman/feather#2]
Hi Richard,

I realise this is awfully early, as you stated in the README already, but I'm interested in building this project and to potentially modify and contribute back.

My experience lies mostly in QML and Python and I have very little experience with CMake, but I figured out how to build it as-is, where it installs files in `/usr/local`, I recorded my experience [here][1].

[1]: https://github.com/mottosso/feather/wiki/Building

But I can't figure out how to build and run without deploying it first. As far as I can tell, the program isn't designed to run with it's source directory hierarchy, such as `main.qml` being in `/ui`.

How, if at all, would you suggest I set things up to build and run?

ps. Regarding bugs and such, I assume it isn't of particular interest to hear about any of that this early on. But if it is, let me know and I'll put them in GitHub issues when/if any pops up.

**Comment by richardlayman** [comment]
Hey mottosso,

Yea, it's still pretty early and I put that there just so people wouldn't think it was finished and be disappointed when they found out it needed a lot of work still. It builds and runs but you need to clone the plugin repository too and build/install that as well; feather is the core application but doesn't contain any of the nodes that are used in the scenegraph - all of those are in the plugin repository. My reasoning for having the nodes outside of the core repository was so that plugin developers didn't have to build the main application to build their node.

You will need Qt5.5 and the Boost Libraries to build the application but that's it.
Building is very simple for both repositories:
  // do this from the root directory of both repos
  $> mkdir build
  $> cd build
  // build the project
  $> cmake ..
  // install the project
  $> sudo make install
  // do the same for the feather-plugins cloned repo
  ...
  // now you can run the application
  $> cd /usr/local/feather
  $> ./feather

When I do the v0.1 release, this will all be cleaned up so it runs like a standard application.
There are still a lot of things missing but you can do simple things like import obj files, work with layers, add and remove nodes and few other basic items but nothing close to a fully functional application yet.
Currently I'm working heavily on scenegraph editor and making it so that nodes can be connected by drag-n-drop. You can't select mesh components yet and will probably be on of the last items added.

My hope is that, once the application is ready, for me (and maybe a few others) to just work on the core application while other people create the nodes for the application - that is why I focused on making node creation as easy as possible. I want the project not to be a end item tool like Blender but rather a tool that the artist uses to create their own tools or tools created by other artist/programmers and for it to be totally independent of the feather project. I know that I'll have to create the first base nodes that will handle basic functionality but I'm hoping more poeple will come alone later and do the heavy lifting for more complex nodes and commands.

Thanks for the interest in feather and ANY help is vastly appreciated. Feel free to contact me anytime with any questions.

**Comment by mottosso** [comment]
Hey @richardlayman, thanks for the reply.

Compiling both of those works just fine, with the exception of the few things I mentioned in [the Wiki][1], and the fact that nothing shows up in the viewport once launched, but it could just be that I don't know which nodes to plug how just yet.

Maybe a short primer of the intended workflow would be in order? If you unlock your Wiki, or add me to the list of contributors so I gain permission, maybe I could help fill it in.

My interest lies primarily in the UI/UX of Feather. In that respect, I'm thinking it might be helpful to implement some lazy reloading of QML files; such as hitting F5 to reload the Component under the cursor. It'd help with rapid prototyping but would require a few things from the backend. It's possible it already fits, I'm not sure. The UI would more or less need to be stateless. Not to mention that the files would need to come from the source directory, as opposed to the deployed directory in `/usr/local`. The latter I think should happen regardless, as it makes tinkering a lot more straightforward.

Either way, it would also be interesting to start looking into the design side of things. How hooked are you on mimicking the look and feel of Wings3d? Just to give you a heads up on where I'd like to go, see [here][2]. :)

[1]: https://github.com/mottosso/feather/wiki/Building/3d4541e9be05769d772f33231e9031f5bb5cd5c9
[2]: https://www.behance.net/gallery/30473933/The-Martian-UI-Screen-Graphics

**Comment by richardlayman** [comment]
I've added you as a contributor feel free to edit the Wiki and push any changes you have.

Are you at least seeing the grid and can move the camera around the viewport or are you just seeing a black screen? Currently you can import obj files and the scenegraph works and can display nodes... but you can't connect the node's fields together to display them in the viewport from the scenegraph editor. Actually the core is pretty functional but the UI features to access these are currently the bottleneck. I have a long list of nodes in the sg editor but the only ones that have been coded has been the Common->Empty, Polygon->Cube and Polygon->Shape and these were done for testing purposes and to show other developers how plugins are created. Currently I'm working on fixing this issue with the sg editor so that you can connect the fields and then they will show up in the viewport. Only Shape nodes will show up in the viewport but you first need to have something plugged into their mesh in field. The exception to this is when you import a obj file and the objects data is put directly into the mesh in field since in fields can hold data with no in connection - sort of like a default value. Currently you will see the root node in the sg editor and outliner but this will be hidden once these issues are straighten out since you should never have to mess with the root node or be able to delete it.

I wouldn't be against having user files located in home or another location but, once deployed, I would like the main application files in common folders used by other applications - /usr/lib, /usr/bin, /usr/share, and user files in ~/.feather
The way that I wrote the application puts all the functionality in the C++ Core. The UI is split into two parts - the QML Wrapper that exposes the core to QML and then QML code that actually draws the interface. The UI QML has very little logic, only enough to draw the display and interact with the wrapper. Most of the wrapper just links core functionality to the QML UI but there are a couple of widgets that I had to make in the wrapper that do work separately of the core - like the outliner model, sg editor and viewport. So basically I want to keep as much logic out of the UI as possible so all you primary see in the qml code is just drawing commands and commands to talk to the wrapper. Another reason for doing this was so that feather could be ran at command line in future since there are many times where a UI is not needed and you just want to do be able to bash script to do the work.

I love Wing's tools but I hate their user interface, so I'm open to a totally different UI. When I started the project it was just going to be a straight up clone of wings just so that it would be easier to move wings usesr over to feather. But I was also working on a node driven animation program and decided it would be easier to combine the two into one project instead of having to maintain two separate projects, so I added a DAG, and then layers, and then commands so it's been slowely moving away from wings for a good while now. It will still have Wings features but it will not be a clone like it was originaly intended to be due to how it works now. Actually, it appears to be moving closer to Maya then Wings.

I looked over the images you linked and they look really nice and if you would like to go for it, then I'm all for it. My main interest is primarily in the core and then the wrapper, so if you wanted to take over the UI, I'm for it; it would take a bunch of work off my shoulders. The current UI is mainly just a test UI and I really don't like it that much and was planning on going back and doing a major cleanup of it anyway just before v0.1 release. The wrappers are written in C++ so if you're missing something, just let me know and I can add it. lib/qml/ holds all the wrapper files that will tell you what you have access to or you can look at the qml files to get an idea. The only file you'll want to ignore is commands.hpp which is used as a link between the wrapper and core - these functions are only used by the wrapper.

**Comment by nemyax** [comment]
Hi Richard,
I've been following the progress of Feather since the beginning, and your
latest email has just made it more exciting.

I was also working on a node driven animation program and decided it would
> be easier to combine the two into one project instead of having to maintain
> two separate projects, so I added a DAG, and then layers, and then commands
> so it's been slowely moving away from wings for a good while now.


Have you got a demo of your animation program? Feather could be a dream
project.


> It will still have Wings features but it will not be a clone like it was
> originaly intended to be due to how it works now. Actually, it appears to
> be moving closer to Maya then Wings.


Whatever happens on the UI front, I hope Feather still retains such Wings
goodies as the ability to have a hotkey for anything and the consistency
across 3D and UV tools.

I don't know if I could be much use as a contributor, but I've done a few
basic plugins for Blender and Wings, so I suppose I would be able to turn
out a couple of tools for Feather if the API is simple.

**Comment by mottosso** [comment]
> Whatever happens on the UI front, I hope Feather still retains such Wings
goodies as the ability to have a hotkey for anything and the consistency
across 3D and UV tools.

+1

> I don't know if I could be much use as a contributor, but I've done a few
basic plugins for Blender and Wings, so I suppose I would be able to turn
out a couple of tools for Feather if the API is simple.

On that note, @richardlayman what does the API look like? How about a short primer? Whether it's finished or not, IMO a document-first approach is healthy, especially if more people would like to contribute.

**Comment by richardlayman** [comment]
@mottosso Yea, documentation is very important but, since I thought no one would start contributing till after v0.1, I was putting it off so I could focus on getting as much of the code done as possible. I'll go ahead and add Doxygen to the project and write the documentation for the wrapper and node's API. There is a short documention on how to make a plugin here https://github.com/richardlayman/feather-plugins/blob/master/base/src/main.cpp This can be used as a base for any new node or command.

>Whatever happens on the UI front, I hope Feather still retains such Wings
>goodies as the ability to have a hotkey for anything and the consistency
>across 3D and UV tools.

Without a doubt; I've used wings since it first came out and think it's probably one of the best modellers out there; I like modeling in it more then blender. I'll want to retain as much of that as possible while adding to it at the same time.

>I don't know if I could be much use as a contributor, but I've done a few
>basic plugins for Blender and Wings, so I suppose I would be able to turn
>out a couple of tools for Feather if the API is simple.

@nemyax If you know C++, creating feather nodes and commands is very simple and you don't even have to build feather to make them since feather's core is a header only library. Even though you can't yet hook nodes up in the sg editor (that will be fixed soon) you can using a command - you can see how this is done by looking at the import_obj command in the obj plugin. Even if you're not a programmer you can still to contribute to the project - there will be a need for asset creators, people to write tutorials, translators, eventually there will be website/forums and people will need to maintain it - but most of this is still in the future.

>Have you got a demo of your animation program? Feather could be a dream project.

It's been pretty much integrated into feather now. Even though I advertise feather as a modeller, that's just a starting point. Once you have DAG where everything this is a node, then what's stopping someone from writing Time node, then a Key node to hold a value, then a Track node that takes the Time and Key/s nodes as input and outputs a value that gets sent to any node's in field... now you have an animation program. Granted, you still need a time line editor, dope sheet editor, key frame editor - but these are all relatively "easy" since they can all be done in QML.

**Comment by nemyax** [comment]
>
> I've used wings since it first came out and think it's probably one of the
> best modellers out there; I like modeling in it more then blender. I'll
> want to retain as much of that as possible while adding to it at the same
> time.
>
> Good to know that you feel this way.

@nemyax <https://github.com/nemyax> If you know C++, creating feather nodes
> and commands is very simple and you don't even have to build feather to
> make them since feather's core is a header only library.


I've only ever done hello-world, but I think I can pick up enough C++ for a
node or two.


> Even if you're not a programmer you can still to contribute to the project
> - there will be a need for asset creators, people to write tutorials,
> translators, eventually there will be website/forums and people will need
> to maintain it - but most of this is still in the future.


Yes, documentation is of the utmost importance.

> Once you have DAG where everything this is a node, then what's stopping
> someone from writing Time node, then a Key node to hold a value, then a
> Track node that takes the Time and Key/s nodes as input and outputs a value
> that gets sent to any node's in field... now you have an animation program.
>
That's what it could be like under the bonnet, but as an animator, you
probably wouldn't want to mess with those things directly. Do you have a
vision for the animation workflow structure and project layout? If not, may
I suggest looking at Hash Animation:Master's project workspace for
inspiration? Animation:Master in its current form is a crash-prone
bug-ridden hackfest, but the original project workspace concept is pure
genius.

**Comment by richardlayman** [comment]
@nemyax 
>That's what it could be like under the bonnet, but as an animator, you probably wouldn't want to mess with those things directly. Do you have a vision for the animation workflow structure and project layout?

I view feather more as a kernel then an application; it's more of something that you use to make the tools you need to use. Obviously most artist are not going to want to make nodes or do any programming, but if the development environment is easy enough you don't need a lot of developers since just one developer can make a lot nodes very easily. I don't see myself reporting to users, rather I should be reporting to plugin developers and they are the ones that report to the users. I'm not going to say feather needs to be this or that; that's up the the users and developers that shape feather - I just have to make sure that feather is flexible, stable, and simple enough for them to use. It won't start out this way since I'm currently the only developer; it will look and perform the way I want it to. But once other people get on board it will start to change and I would be happy to turn it over to the community and then I would just manage the kernel and let them decide what feather will be. I see there being a vanilla feather that you download which gives you the most commons plugins but I can also see there being projects totally separate of feather for very complex nodes that have their own repository and you would go to them to get their nodes.

>Animation:Master in its current form is a crash-prone bug-ridden hackfest, but the original project workspace concept is pure genius.

I've never used Animation Master, I was using Maya during the time AM was in it's prime. But I remember it being very popular for a good while - someone actually got a job at Pixar for a viral animation done in Animation Master. That's not that big of a deal now, but back in the day there was a huge gap between the different software packages and it was really impressive.

**Comment by richardlayman** [comment]
@mottosso I've added Doxygen to the project, it will build when you run make and put the documentation into the project's root doc/api folder. I still need to write the doc for the functions and such - will work on that this weekend.

**Comment by mottosso** [comment]
Thanks for the heads up @richardlayman.

I could have a look at getting the docs up on GitHub Pages for some free hosting and address, such that we could look at it in unison and link to relevant parts in issues and Wiki and such.

Thoughts?

**Comment by richardlayman** [comment]
@mottosso I have a io page for feather now - https://feather3d.github.io and I also got the feather3d.org domain name a while ago and have it on a private host with sql for forums... but I haven't had any time to do any work on it since I've been focused on coding. I also have a feather organization setup as well which I will move the repositories over to later. I sent you an invite to the organization which will give you access to the io page. I'm not a web designer so hopefully I can find someone in future to snazzy it up.

**Comment by mottosso** [comment]
Got the invite, sent you one as well, to a chat platform called Gitter. I use it for my projects and found it useful for direct communication, here's an example.

- https://gitter.im/pyblish/pyblish

It..

- Is free
- Has browsable history that you can link to
- Notifies you on messages, given the page is open
- Supports markdown
- Supports syntax highlighting, so we can post code and junk

For a forum, how about Discourse? I'm using this too and find it good for persistent conversations, see here for an example.

- http://forums.pyblish.com

It..

- Is also free
- Looks good
- Notifies you on messages, given the page is open
- Supports markdown
- Supports syntax highlighting

Setting up discourse is more work, but I could have a look at it if you want. You'll need SSH access to your a computer at your hosting provider.

**Comment by richardlayman** [comment]
@mottosso got your invite and it works fine, glitter looks pretty good and I'll give it a try - looks better then irc.

I've had my host for a very long time and used to be on a higher tier but they have moved me down and I don't have ssh access anymore and will cost me an extra $24 a year. I'm thinking of changing hosts because I'm sure there are better ones out there now for the same cost with better features and is more up-to-date; their site looks the same as it did ten years ago. I'm currently spending $110 per year on my host, I'm sure I can find something better for that same cost.

Discourse looks pretty good too, but I think I'll hold off till after v0.1 is released unless someone else can do it.

**Comment by mottosso** [comment]
I've recently been through this "swamp" of technology and service choices and might be able to provide some insight.

Firstly, if you're going with GitHub Pages for hosting, you'll do fine with just the domain name and linking it to that. For Discourse, you'll need an empty shell of a computer with SSH access; not any OS will do, it needs to be a rather recent edition with support for dependent software.

There is Digital Ocean, which is $5/month, but requires installing the OS and setting up surrounding infrastructure for hosting a web application such as Discourse yourself. I could set that up for you if are willing to take on the service cost, it'll take about an hour or two to finalise and maintenance so far has been less than 20 mins total in a year.

At that point, you could be paying whatever your domain name costs plus the cost of DO which should total around half of what you're paying now per year. Minus Discourse, and you're down to just the domain name, but $5 isn't a lot of money compared to what you're getting in return IMO.

**Comment by richardlayman** [comment]
That sounds pretty nice and I have no problem picking up the cost if you were willing to set it up. But there is one thing that kind of turns me off and that's bandwidth. Currently I have 14T on my current host but only 1T on DO. For forums that's not an issue but I still like having the extra bandwidth in case I want to transferring large files and other things - I've easily past 1T in the past on my current host even though it's pretty dormant now. I'll have to look into it some more.

**Comment by mottosso** [comment]
In general I wouldn't worry about hosting large files, there are so many services out there today that does that for free; even in the multi-gigabyte range.

This one for example.
- http://bintray.com

A service like that is both more reliable in terms of uptime and fast in terms of bandwidth than anything we could realistically hack together without significant effort.

Also, I remember reading that DO doesn't actually enforce bandwidth limits, even though they advertise them along with their pricing. But it isn't something I've stress tested.

**Comment by richardlayman** [comment]
If they don't enforce their bandwidth limits, I'm good with that. Realistically I very rarely exceed 1T but I like having the safety net just in case. Bintray looks good too and would be nice to host different packages of feather on. I'm going to be the maintainer of the Arch package which will be hosted by Arch's AUR repository until it can get onto it's main repository, but I'm sure there will be other packages and eventually someone will do a windows or apple build that will need to be hosted - these could eat a lot of bandwidth. Plus I would like to have a place where people can host their plugins as well so they are on a single stable host and don't have to worry about a plugin disappearing overnight because someone canceled their host or something else happened. So IO for the site, DO/Discourse for the forums, and Bintray for the packages/plugins. I still want to do some more research on it but that sounds pretty good, what do you think?

Were you planning on using the free version of Discourse?

**Comment by mottosso** [comment]
Here, found the link where they claimed not to charge for bandwidth.

- https://www.digitalocean.com/community/questions/billing-for-bandwidth-overage

> So IO for the site, DO/Discourse for the forums, and Bintray for the packages/plugins. I still want to do some more research on it but that sounds pretty good, what do you think?

I'm all for it, that's the best combination I can think of!

Down the line, I would probably look into mirroring each build elsewhere, like on Dropbox, to make sure it really never goes down or disappears, say 5+ years from now.

But at the moment I think hosting it on GitHub directly, via their releases system, will suffice. It's also capable of an arbitrary amount of files (and sizes, below 1 gb each I think), both manually and automatically deployed via things like Travis and AppVeyor.

**Comment by mottosso** [comment]
> Were you planning on using the free version of Discourse?

Discourse the software is free, it's the hosting they charge for. But we'll be doing that ourselves.

If you hand me login details for a DO account, I can have a look at booting up a "droplet" and installing Discourse this weekend. Alternatively, setup one yourself (Ubuntu 14.04 with Docker pre-installed) and hand me the login details. My mail is in the profile or on Gitter via private message if you prefer.

Actually, may I refer you to Digital Ocean? It looks like you'll get $10 if I do, and I'll get $25. Win win. :)

**Comment by mottosso** [comment]
For completeness, here's a link to the forums.

- http://forums.feather3d.org

I'll be back on this horse from next week and will look towards understanding the QML codebase.

Here's another thought; I noticed a few bug-fixes in recent commits and am thinking it might be a good idea to first create an issue about it, such that it can be referenced in the commit but also followed by others. Not to mention that issues may get logged and not immediately fixed by you, such that someone else (e.g. me!) might hop on and get started in that way. What do you think?

**Comment by mottosso** [comment]
Something is currently up with the domain name.

`ERR_NAME_RESOLUTION_FAILED`

Here's the direct address.

- http://162.243.2.203/

I can set-up a service to check every so often whether the address is still up? It's really useful, it'll tell you when things go down so we can fix it more quickly. It's free as well.

- https://uptimerobot.com/

**Comment by richardlayman** [comment]
@mottosso 
Not sure what's going on with the name, it was working till just a couple of days ago. I checked my host and nothing changed and everything still looks good. I sent the info to the DNS servers again to see if that would fix it but I'll have to wait till they update to see if it worked. There is a setting for the name for different types [A,CFRAME,URL NAME,URL FORWARD,TXT,AAAA] I had it set to A but now changed it to URL FORWARD to see if that would help.

>Here's another thought; I noticed a few bug-fixes in recent commits and am thinking it might be a good idea to first create an issue about it, such that it can be referenced in the commit but also followed by others. Not to mention that issues may get logged and not immediately fixed by you, such that someone else (e.g. me!) might hop on and get started in that way. What do you think?

Yea, that's a good idea. I wasn't doing this because no-one was working on the code besides me and I wanted to focus on getting as much coding done as possible. I knew that, once people started getting interested, I would have to do this but I wanted to hold out for as long as possible. But it looks like I should start doing this soon now.

>I'll be back on this horse from next week and will look towards understanding the QML codebase.

No prob, I still have a lot of work to do so you have plenty of time.

**Comment by mottosso** [comment]
> There is a setting for the name for different types [A,CFRAME,URL NAME,URL FORWARD,TXT,AAAA] I had it set to A but now changed it to URL FORWARD to see if that would help.

It should really be "A". Forwarding might look like it works, but might confuse web crawlers and more advanced power users. It's on a fixed IP so for the time being it probably isn't much of an issue, but let's find out. :)

> I wasn't doing this because no-one was working on the code besides me

Yeah, kind of a chicken-or-egg problem I suppose.

I find it difficult to jump in without knowing what's going on, but why bother documenting things if no one is there to see it? I find it helpful to always act as though everyone is watching at all times. In my case it makes for better code, even if no one will ever look.

**Comment by richardlayman** [comment]
Ok, my DNS updated and it forwarded fine - I'm in Minneapolis on a business trip so I can see the changes much faster now (minutes instead of hours). I reset it back to A to see if it would start working again properly.

**Comment by richardlayman** [comment]
Ok, it's back to working correctly now. Not sure why this happened in the first place, the only thing I can think of is my host had it accidently cleared even though it still showed up on the site correctly. I'll have to keep an eye on it.

**Comment by mottosso** [comment]
Working here as well!

> I'll have to keep an eye on it.

That's what uptimerobot is for. :)
