### ISSUE TITLE
SceneGraphEditor in QML

### ISSUE THREAD

**Issue by mottosso** [richardlayman/feather#4]
I noticed in [the Wiki](https://github.com/richardlayman/feather/wiki/UI-Development) that you mention that the scene graph editor was written in C++ rather than QML due to performance constraints.

I've been curious about implementing an editor in QML in the past and wouldn't have thought it to be too slow; do you still have the performance comparisons available? I'd be interested in giving it one more go, just so we're sure. It would be a shame to limit QML-designers from editing everything except the thing that pretty much matters the most.

**Comment by richardlayman** [comment]
There are a couple reasons why qml is not a good choice for the SG in my opinion. Speed is obviously the most important thing - the SG has a straight shot for the core in C++ but has to go through the Qt wrapper for QML. Another reason is that it puts a lot of logic code into the UI which I want to stay away from as much as possible to make it easier for poeple that want to modify the UI. The QML should only be changing what the nodes look like, the colors, and background - the reset should be handled by the editor widget. Not all of the SG is done with the C++ widget; the popups and various other connection info is displayed using QML - only the nodes and connections are in C++. Most of these speed issues whould not be seen with just a few nodes, but when you start getting into a lot of nodes with complex connections, the difference will start to compound. Also, and I think you probably already know this, the SG editor C++ widget representing the graph and is a QML item that you use within the SG editor; the rest is done in QML (menus, toolbars, etc.).

**Comment by mottosso** [comment]
> Speed is obviously the most important thing - the SG has a straight shot for the core in C++ but has to go through the Qt wrapper for QML

Are you sure this is a performance bottleneck that you've actually tested?

> Another reason is that it puts a lot of logic code into the UI

I agree with this sentiment; QML should contain no business logic at all under ideal circumstances. But I'm not sure it has to come to that.

The way I'm imagining this to work, is for there to be a model, such as the QAbstractItemModel, which would contain all data and logic for handling that data; such as making or breaking connections. The UI then would merely trigger such an event, with an appropriate description of which nodes requests a connection from which attribute to which other attribute.

That way, QML contains only UI logic, such as when to start drawing an edge and how large the animated circle would be when hovering a compatible endpoint, which I think is a good, and expected, place for it.

> but when you start getting into a lot of nodes with complex connections, the difference will start to compound.

I can see what you mean, but I'm not sure I agree.

With an appropriate use of the loader, we could (quite easily, I think) ensure that only visible nodes are drawn and drawn at an appropriate LOD based on their size.

Just like how the ListView currently handles trillions of items, but really only draws the few that are currently in view.

The reason I feel so strongly that the graph editor needs to be in QML, is because of how important the interaction and look of it is to the overall sense of Feather. Take Maya for example; most of it is regular Widgets, but it's Hypershade and Node Editor are instances of QGraphicsScene. This means you can't tweak their look and that they are bound to remain identical to users looking to customise and even to those within the company, because only those with sharp C++ skills will ever be able to modify it's look (and feel).

I see Feather standing out from the crowd here (and perhaps even take the lead).

**Comment by richardlayman** [comment]
>Are you sure this is a performance bottleneck that you've actually tested?

This comes from my experiences using runtime languages vs C/C++. When I wrote Maya plugins they tended to be x10 faster then their MEL equivalent; Alias even stated this in their docs. I did a bunch of testing of 3d data importing/exporting and OpenGL in Python - C/C++ was around x5 to x10 faster every time. I tried Ruby (granted, Ruby is not known for it's speed) and it was worse. One thing that has always hurt Wings was that it was written in Erlang which makes it very slow and hard to work with when you're dealing with huge models - the original developer even pointed this out and said, if he knew the languages, he would have coded it in C or C++. There's always been this huge difference between compile time and runtime languages. Hardware has gotten much more powerful making this harder to see till until you get into the very large data sets; it's not uncommon for me crash Wings with models that Blender can easily handle and that's not because Wings is broken; it's because they are using Erlang to handle their data. When I first started using UI toolkits, I started with GTK and then Wx before moving to Qt. During this time I was using doing all my UI's in C++ till QML came around. Even Qt states that any heavy data should be handled with C++ and exposed to QML. I'll be the first to admit that I'm a bit biased on this subject so I could be wrong.

>The way I'm imagining this to work, is for there to be a model, such as the QAbstractItemModel, which would contain all data and logic for handling that data; such as making or breaking connections. The UI then would merely trigger such an event, with an appropriate description of which nodes requests a connection from which attribute to which other attribute.

That's not a problem since I already have QAbstractItemModels used in the wrapper for the Outliner data and field editor, so it wouldn't be a stretch to make one for the sg. But I'm wondering how this would be laid out since it couldn't be a tree due to how the nodes are connected. It seems like it would have to be a list model where each item contained <Uid,Nid, inFids, outFids,connections> or it could contain a list model of just the connections and each item would have <sUid,sFid,tUid,tFid> you could then get the node info using the uid and fid values. What do you think?

>With an appropriate use of the loader, we could (quite easily, I think) ensure that only visible nodes are drawn and drawn at an appropriate LOD based on their size.

This is true; you do have a point there.

>The reason I feel so strongly that the graph editor needs to be in QML, is because of how important the interaction and look of it is to the overall sense of Feather. Take Maya for example; most of it is regular Widgets, but it's Hypershade and Node Editor are instances of QGraphicsScene. This means you can't tweak their look and that they are bound to remain identical to users looking to customise and even to those within the company, because only those with sharp C++ skills will ever be able to modify it's look (and feel).

Is Maya using Qt now? It's been so long since I used it. They were using MEL when I using it and later added Python after I left. I have no problem giving it a go and see what happens; we can do the sg editor all in QML using models to expose the core data. If we do end up having issues, we can go back to C++ for v2.0. It's pretty much a given now that v1.0 is the prototype and there's usually a rewrite for v2.0 (Lux, Blender, Python... well v3.0 for Python). So we can go ahead and try this with all the widgets and see how it affects application and tweak as needed.

**Comment by nemyax** [comment]
>
> the original developer even pointed this out and said, if he knew the
> languages, he would have coded it in C or C++.


He did know them very well. Here's what he wrote on the topic:


> C/C++ was out from the start. I wanted a language with automatic memory
> handling so that I didn't have to worry about allocating/freeing memory
> myself, and I didn't want to spend a lot of time in low-level debugging to
> find pointer errors and memory leaks (I do enough of that in my day work,
> so I didn't want to do that in my spare time too).
>
> My idea for implementing multiple Undos would not work in Java, so Java
> was also out.
>
> Since I know Erlang very well (since I work with Erlang's run-time system
> and Erlang compiler in my day work), Erlang was the natural choice.
>
> Other possible choices would have been Scheme or Lisp, but I don't know
> those languages nearly as well as I know Erlang. (Although Scheme and Lisp
> can be used in a functional style, they can be used in an imperative style
> as well; the mix of imperative and functional style (properly used) could
> have had advantages. A disadvantage with Lisp/Scheme is that there is no
> pattern matching.) An interesting language if I had started today would be
> Haskell.


I wish it had been Haskell from the start.

**Comment by richardlayman** [comment]
>He did know them very well. Here's what he wrote on the topic:

My apologies, I was going off of my memory on something I read many years ago. I didn't mean to say that he didn't know the languages rather that Erlang was his main language. I work with C/C++ in my day job so allocating/freeing memory and low-level debugging is not a problem for me and I don't mind it. In fact I think these issues are kind of blown out of proportion many times. But the end result is still true that Wings speed issues, when it comes to large data sets, stems from Erlang. I've never messed with Haskell so I can't say if that would be a better choice or not.

**Comment by mottosso** [comment]
> This comes from my experiences using runtime languages vs C/C++.

Granted, C++ is faster than JavaScript. But this paragraph is much too general.

Even in QML, all of the heavy calculations are still done in C++; in particular, the updating and drawing of the canvas and all of the nodes. Regardless of how many nodes you throw in there, QML would render it on it's own via C++ and OpenGL, regardless of whether JavaScript was the one to trigger that action, or C++. This is how I've been using Python with Qt for many years; Python is far from fast enough to render any of that, but logic is only a small fraction of the compute cycle.

In fact, as you are using QQuickPaintedItem (which is basically QPainter) I'd argue that you would *gain* performance by building it using regular rectangles, which would end up in the SceneGraph as geometry and properly processed by OpenGL, as opposed to first being rendered to a texture from C++ and later exported to OpenGL and assigned to a rectangle, which it would be doing currently.

In the end it doesn't hurt to test. I'll mock something up within the coming days and maybe we could talk about how to optimise it. One of the things I'm not sure of however is this:

> It seems like it would have to be a list model where each item contained or it could contain a list model of just the connections and each item would have you could then get the node info using the uid and fid values. What do you think?

I would mock things up in Python, as it's the language I'm most familiar with, but perhaps you could guide me in how to produce a model fit for a graph? I'll handle the drawing, LODs and culling via QML.

**Comment by richardlayman** [comment]
>In the end it doesn't hurt to test. I'll mock something up within the coming days and maybe we could talk about how to optimise it. One of the things I'm not sure of however is this:

>>    It seems like it would have to be a list model where each item contained or it could contain a list model of just the connections and each item would have you could then get the node info using the uid and fid values. What do you think?

Whoops! GitHub erased some of the info that I had put in because I wrapped them with '<>', it was supposed to read like this.

>It seems like it would have to be a list model where each item contained { uid, nid, connections } or it could contain a list model of just the connections and each item would have { sUid, sFid, tUid, tFid } you could then get the node info using the uid and fid values. What do you think?

**Comment by mottosso** [comment]
Actually I couldn't contain myself, here's an implementation of a minimal scene graph; or really just a bunch or rectangles to test performance.

![](https://cloud.githubusercontent.com/assets/2152766/11446066/3564b438-952a-11e5-91bb-37d01c1f68b2.gif)

- https://gist.github.com/mottosso/fc0149224b21c22061fe

I get up to about 300 nodes before the application chokes. I'm not sure whether it's because of Python or QML, so maybe you could have a look at doing something similar via C++ to know for sure?

I'd be interested in continuing on, adding connections and things, but I can't wrap my head around how that would work. Not overly familiar with graph theory and adjacency matrices, or however you made your scenegraph. Hopefully the Python code is self-explanatory, maybe you could give me an idea of how to proceed?

**Comment by richardlayman** [comment]
That's looking pretty good, we'll have to see how it holds up once icons, connections and other graphics are applied.

Virtually all the functionality is there now to draw a full SG.
There is always, at least, one node called the 'root' node. I currently showing this but it will get hidden on release since the user can't work on it and there's no reason to show it.
On startup, or a new scene, this is the default selected node. To get a list of all the connected nodes you would use this:

    import feather.scenegraph 1.0
    import feather.node 1.0
    import feather.field 1.0
    ...
    // get the uid of the selected node
    var uid = SceneGraph.selected_node()

    // now you can get it's name
    var name = SceneGraph.node_name(uid)

    // and what type(nid) of node it is
    var nid = SceneGraph.node_id(uid)

    // you can now get the node's info - note: this is info on the node type, not any uid info
    Node { id: node; nid: nid } // note: this is a WIP

    // you now have access to the in and out fields - note: this is info on the field type for a given node type
    var subX = node.inFields[0]
    // you can now look at a field's attributes
    var subXFid = subX.fid
    var subXType = subX.type

    // but you have to use the scenegraph to get it's dynamic data
    // like if it's connected
    var connected = SceneGraph.connected(uid,subX.fid)
    // what nodes is it connected to
    var tuids = SceneGraph.connected_nodes(uid,subX.fid)

    // you now repeat the process like above to get the info for each target uid and each fid in that node

NOTE: some of the above functions are not avaible yet since I haven't moved them over from the sg editor, but I'll be doing that day and it shouldn't take that long since it's just moving code around.

In my UI I had a ListModel that mapped the node names to the nid's go they could be looked up, like this { name: "PolyPlane"; nid: 321 }.
I then had another model that I used to look up the fids for a given nid { name: "subX"; nid: 321; fid: 1 }, ...

**Comment by richardlayman** [comment]
I updated the SceneGraph, Node and Field qml items. I'll update the Wiki tomorrow to explain the changes.

**Comment by mottosso** [comment]
> To get a list of all the connected nodes you would use this:

Hm, I wonder whether this wouldn't be better suited as a QAbstract*Model?

It looks like what you have here is a lot of functionality from the scenegraph model spilling over into QML, like specific function names asking for specific things with specific IDs. The QAbstract*Model hides all of that.

If you look at my example, you'll see how certain strings, like "name", map to the model returning certain data. What do you think about wrapping up your scenegraph like this, where asking for "name" simply returns the name of the node currently being queried.

The most important thing being, I think, that the "selection" and traversing the graph and things is done in C++, the QML delegate simply manages the outcome of that and draws it.

Would you like me to mock up an example? Not sure how familiar you are with the QAbstract*Models, maybe I'm missing something in your example.

**Comment by richardlayman** [comment]
The function calls are there so that the user can use them to create their own scripts in the UI. Also, there are times that you may only want to know a certain thing - like node.in_field_count() is simpler and faster for the user then searching through a model if that's all you need to know.

>If you look at my example, you'll see how certain strings, like "name", map to the model returning certain data. What do you think about wrapping up your scenegraph like this, where asking for "name" simply returns the name of the node currently being queried.

I already use a QAbstract*Model on several things, it's not a problem to create another one. The DAG poses some unique issues in that's hard to represent it as a table since connections can jump over to other branches. There could be three QAbstartItemModels - one for the hash layout based on parent/child { name: string; uid: int; nid: int; x: int; y: int; in: fields[]; out: fields[]; links: connection[] }. The fields[] would consist of { name: string; fid: int; connected: bool; type: int; connection: int } and connections would be { sfid: int; tuid: int; tfid; type: int }. This is the best I can come up with at the moment. Models are good for tables and lists but DAGs are a little different and will require some extra coding in QML. Whatever you need I can make, so just let me know what you need.

There's also the issue on how is the SG editor is even going to work. So far I've tried two methods - one where the nodes only had one in and out field and another where all it's in and out fields were shown. I think that the one with only one in and out field looked the best; the one where all the fields were shown seemed to clutter the screen once there started to be more then ten fields. So currently the idea is to RClick on the out connection which pops up the field list color coded by type and displaying each field name. The user LClick the field they want to use and then a connection is created between the out connection and linked to the mouse point. The user will move the mouse point over the in connection of another node, RClick to display a list of all the fields that can connect to this type field. The user would then LClick on the item they want to connect to and the popup would go away and new connection made if one didn't already exist. Let me know how you feel about this or how you see this working.

**Comment by mottosso** [comment]
> like `node.in_field_count()` is simpler and faster for the user then searching through a model if that's all you need to know.

I suppose I just can't picture a scenario where you would need to know about that.

Let me know if I'm missing something, but to me it seems like the count could remain implicit through the model.

```qml
/* Creating a drop-down menu for a node */
ListView {
  id: menu
  model: node
  delegate: Text {
    // count is implicit
    text: name // Name is fetched directly from the current item in the model
  }
}
```

> The DAG poses some unique issues in that's hard to represent it as a table since connections can jump over to other branches.

I can believe that, I really have no idea, but mocked up an example where there are two models and two views; one for nodes and the other for connections.

[![untitled](https://cloud.githubusercontent.com/assets/2152766/11457163/bd1a3a04-9699-11e5-8426-0a96c8c1eb3e.gif)](https://gist.github.com/mottosso/d5a95bc89460bf2c88b6)

- https://gist.github.com/mottosso/d5a95bc89460bf2c88b6

> There's also the issue on how is the SG editor is even going to work. 

Yes, an important question and one we should probably nail down as soon as possible.

For starters, here's a summary of all nodal interfaces out there.
- http://blog.interfacevision.com/design/design-visual-progarmming-languages-snapshots/

There are likely more, here's at least one more of particular interest that looks good and is written with QML.

- http://flowbox.io/

![image](https://cloud.githubusercontent.com/assets/2152766/11457292/cffa50d4-969c-11e5-9585-01190c2949c5.png)

Other than that, I am also torn between having each node visualise its inputs/outputs - like Houdini's VEX.

![image](https://cloud.githubusercontent.com/assets/2152766/11457261/f60f1706-969b-11e5-8ae3-8aad7ee9ceb9.png)

Or whether it should just be a more general box with a single connection going into it; like Maya's HyperShade.

![image](https://cloud.githubusercontent.com/assets/2152766/11457259/ed023a3a-969b-11e5-9834-6f49d3879c7b.png)

But if there's one interface that I'm not a particular fan of - which is unfortunately popular today - it would be the Softimage ICE interface, including Maya's new Node Editor.

![image](https://cloud.githubusercontent.com/assets/2152766/11457270/55ec23e4-969c-11e5-8adf-b331777b0efb.png)

VEX and ICE share that they both visualise their slots, but VEX is much cleaner IMO. Having said that, I've always been more comfortable with Maya's look, and how Houdini does it outside of VEX.

![image](https://cloud.githubusercontent.com/assets/2152766/11457285/9924f6fe-969c-11e5-8946-a92da32f4b76.png)

However in this case, the lack of slots often result in implicit connections via scripting..

**Comment by richardlayman** [comment]
>I suppose I just can't picture a scenario where you would need to know about that.

in_field_count() was just an example. What I was trying to say was that when the user is writting scripts they will, many times, just need to know a specific thing and it's easier for them to just use SceneGraph and grab that value then go through a Model... in my opinion.

>I can believe that, I really have no idea, but mocked up an example where there are two models and two views; one for nodes and the other for connections.

I had thought of that as well where there would be two models - one for nodes and one for just the connections. Either way it's not an issue; I can get you anything you need.

I've never messed with Houdini's VEX before but I have to say, from the examples you posted, it looks the best out of the bunch eventhough it's showing every connection. I like Maya's HyperShade but that's more out of my own bias towards Maya; there's still a few things about it that I think could be better. What I don't like about the HyperShade is that it has straight line connections, it shows every connection but not what attributes are connected which ends up cluttered the screen, the nodes are too big. I like the idea of just showing one connection for all the connections but we also have to limit how many times a user needs to click on something before they get the desired result. In my first example it took 4 clicks to connect two nodes - idealy it should be 1. The only way I see of doing that is to show the all the fields and the user would LeftPress and drag-n-drop to the other node's in field. From the above examples VEX was the only one, that it appears, could do that. Oddely enough, my SG was looking more like SoftImage's and I was having the same issue with it as the example image that you posted above; it's too cluttered - I mean, can you really tell where all those green connections are going unless you concentrate. I had a thought of an idea where there would be only one in/out connections and the user would RightClick to expand the node which whould, in turn, expend all the node's it's directly connected to. Also, I'm very much for coloring the nodes and their fields based on their type. The human eye can pick up colors faster then it can read text and I would like to have it so that the user can quickly see what the SG they need to pay attention to instead of having to read every field connection name. I see the colors as a way of guiding the user, as if saying - 'if your looking for Vertex3D, I'm over here' and then the user would read those fields to see the exact one they need. I also has this with my FieldEditor and LayerEditor in my UI; colors play a very important role for me when it comes to identifying node and field types. I'm also very much for icons being used to identify nodes as well; I believe someone can tell what a node is faster by an image then text. Text is still very important, don't get me wrong, but it should be the last thing the user looks at in my opinion.

I think on the track with your SG.

**Comment by mottosso** [comment]
> Also, I'm very much for coloring the nodes and their fields based on their type. 

Agreed. We should make a list.

- https://github.com/feather3d/feather-ui/wiki

> I like the idea of just showing one connection for all the connections but we also have to limit how many times a user needs to click on something before they get the desired result.

I'm with you on this, but I also think there's a middle ground in terms of node interfaces like these.

Like with code, I think a graph is read more often than it is modified. In this spirit, clicking 3 times as opposed to 1 when in return you read it 3 times faster maybe isn't a bad thing. That's what I like about HyperShade versus ICE.

> I've never messed with Houdini's VEX before but I have to say, from the examples you posted, it looks the best out of the bunch eventhough it's showing every connection. 

I like it too, and think we should go for that. But take a moment to have a look at the link I posted as well, with all possible layouts gathered. Maybe there is one in there which more closely resembles your vision for how Feather should work.

Hopefully, if we do it in QML, replacing it, or even having multiple alternatives, should be fairly straightforward. But it doesn't hurt to get a good approximation to start off with.

**Comment by richardlayman** [comment]
>I like it too, and think we should go for that. But take a moment to have a look at the link I posted as well, with all possible layouts gathered. Maybe there is one in there which more closely resembles your vision for how Feather should work.

Yea I looked at those yesterday, never realized there were so many DAG's. I still have to say that Houdini's looked the best in my opinion.

>Like with code, I think a graph is read more often than it is modified. In this spirit, clicking 3 times as opposed to 1 when in return you read it 3 times faster maybe isn't a bad thing. That's what I like about HyperShade versus ICE.

I can't speak for everyone, we all work differently, but I spent most of my time in the HyperShade and Blender's node editor just connecting nodes, so that's why I'm so focused on how things will be connected.

>Hopefully, if we do it in QML, replacing it, or even having multiple alternatives, should be fairly straightforward. But it doesn't hurt to get a good approximation to start off with.

I agree, we don't have to get it right the first time; I'm sure more people will come along with ideas and suggestions that will need to be implemented later.

**Comment by mottosso** [comment]
About having curved lines as opposed to straight, I've done some research about this in the past and come up empty handed. There simply doesn't seem to be any good support for OpenGL drawing of lines in QML for some reason. And drawing via Canvas is a no-go because of the performance bottleneck that would incur as Canvas is a 2d rendering to a texture onto a plane, as oppose to something like a GL_STRIP.

But I just came across this which made me very happy.
http://qt.apidoc.info/5.1.1/qtquick/scenegraph-customgeometry.html

What do you think about implementing this? Not necessarily right away, as I think straight lines is a good start, but maybe down the line (pun!).

**Comment by richardlayman** [comment]
No problem, I'll have it in by the end of tomorrow. For me, curved lines make the SG much easier to look and decipher so they are very important; Maya's straight line connections always drove me crazy for some reason.

**Comment by richardlayman** [comment]
@mottosso Added bezier curve to the qml wrapper.
https://github.com/feather3d/feather/commit/3e011fb818c6d51a1fbdc0a697a0b997ea92e0fa

Same as the example you provided except you use the below line below to import it.

    import feather.ui.curves 1.0

**Comment by mottosso** [comment]
Cool, will have a look at that.
