### ISSUE TITLE
QML Reload

### ISSUE THREAD

**Issue by mottosso** [richardlayman/feather#5]
As I was working on demoing this particular feature to you yesterday, I came across some difficulties related to how QML decides to cache things and that you don't seem to be able to do this in QML-only but instead need to expose a QmlEngine function that you need to call inbetween destroying an old copy and creating it again.

Then I came across this.

- http://www.ics.com/webinars/how-best-realize-runtime-reload-qml

Ultimately, I think this is essential if we are to manage to design anything useful without having to rebuild/reinstall each time a change is made.

Here's an illustration of how I'd imagine this feature to work.

```qml
/* 
    Hovering with the cursor and pressing F5 causes the component
    under the cursor to reload. However, due to implicit caching, the
    file is not refreshed.
*/
import QtQuick 2.5
import QtQuick.Controls 1.2
import QtQuick.Layouts 1.1
import QtQuick.Window 2.2

ApplicationWindow {
    id: window
    width: 300
    height: 200
    visible: true
    title: "Feather 0.1"

    Row {
        id: sv
        anchors.fill: parent

        Loader {
            property string path: "SceneGraphEditor.qml"

            width: 150
            height: 200
            objectName: "scenegraph"
            source: path
        }

        Loader {
            property string path: "Viewport.qml"

            width: 150
            height: 200
            objectName: "viewport"
            source: path
        }
    }

    MouseArea {
        id: ma
        anchors.fill: parent
        hoverEnabled: true
    }

    Action {
        shortcut: "F5"
        onTriggered: {

            var loader = sv.childAt(ma.mouseX, ma.mouseY)
            print("Reloading ", loader.path)

            loader.setSource("");
            /* Trim internal cache here! */
            loader.setSource(loader.path)
        }
    }
}
```

- [Reference on trimming the cache](http://stackoverflow.com/questions/19604552/qml-loader-not-shows-changes-on-qml-file)

**Comment by mottosso** [comment]
I went ahead and implemented this example in PyQt.

- https://gist.github.com/mottosso/fa01c80080363df3433d

**Comment by richardlayman** [comment]
I not sure how is this helpful with the sg editor or the viewport editor since they never change. I guess what I'm asking is why would we ever need to reload the QML files; the only time I could think of that the UI would need to be reloaded would be when a plugin is added or removed, but that would be rare since most people would not be adding or removing plugins that often. And any changes we make to the QML is going to be from the project repo so it's going to have to reinstalled. The core doesn't have to rebuilt is just the QML was changed. What am I missing?

**Comment by mottosso** [comment]
The SG editor and Viewport were just examples I used to get the general idea across, this should ideally apply to all components; though I'd still see a use for them to be reloadable.

Here's what you missed; I meant for this to be for developers, not the end user.

Currently, when I make a change to QML, I must reinstall to see the change. Worse yet, when I add a new QML file, I must both cmake and install. This is probably how things are usually handled with C++ projects, but there's a better way. Reloading would not only make iterations faster, it would also enable those who don't know much about compiling (e.g. designers) to contribute and work on the code.

> And any changes we make to the QML is going to be from the project repo so it's going to have to reinstalled.

This bring me to my next issue. What do you think about there being a "debug mode" of sorts where Feather is fetching as much of its resources as possible from the source directory; primarily all of the QML files and images? If there were, this could work and iteration times would skyrocket!

**Comment by richardlayman** [comment]
What do you think of spliting the UI from the feather repo. The feather repo would only contain the C++ core code and any wrappers needed, such as the QML wrapper. So there would be three repos feather, feather-ui and feather-plugins. This would make it possible UI developers to fork the UI and not have to worry about the cmake or building the core since they could get that in a pre-compiled package from their distro repo. The core would still have the Qt C++ main but it would only be exposing the core functions and starting the main.qml from a certain location - after that it would all be the UI's reposiblity and you could structure it anyway you wanted. How does that sound?

**Comment by mottosso** [comment]
Yeah, that could work!

Would it be possible then to run the application, using the QML files from the repo directly, as opposed to installing it first?

**Comment by richardlayman** [comment]
As long as the feather exe can find the main.qml it shouldn't be a problem; there are no hardcoded paths beyond that. Note, the core doesn't support text like node and field names - that's the responsiblity of the UI due to translation issues. The SG uses ints to id it's nodes(nid) and fields(fid), this later gets tied to a name in the UI. When a file is saved, only these int values(uid's) are saved, not the name node or field type names - the exception being any text that the user inputs like a unique name for a node or field(feather supports add/remove fields). So if there was a PolyPlane node, 'subX', 'subY', 'parent', 'child', 'meshOut' and 'PolyPlane' would be stored in the UI so it can be translated but it's name - lets say 'myPlane' would not and would be saved in the feather file whenever the user went to save the scene.

**Comment by mottosso** [comment]
Cool, let's do it.

> Note, the core doesn't support text like node and field names - that's the responsiblity of the UI due to translation issues. The SG uses ints to id it's nodes(nid) and fields(fid), this later gets tied to a name in the UI.

Replying to this [here](https://github.com/feather3d/feather/issues/4#issuecomment-160189600) as it sounds like a similar topic.

**Comment by richardlayman** [comment]
Ok, I'll go ahead and make a new repo for just the UI. I'm still using my original UI until the new UI gets up and going. I'm going to put in a build flag into the build that will switch between legacy or new (defaulted to new). Once the new UI is up and running I'll remove the legacy UI from the feather repo and remove the build flags for it. I'll also be adding a config file that will allow you point to the directory with the main.qml file you want as the entry point. This could come in handing if you wanted to have different versions of the UI or just test a certain item. The new repo will be empty; you can make it however you like.

**Comment by richardlayman** [comment]
Ok, feather-ui is ready to use. I made three teams - Site, Core, UI and Plugins. You are only in the Site and UI teams and have read/write privileges. If you would like to be in any of the other teams, let me know. I set the .gitignore to Qt and license to GPL v3 with a README.md file, so you should be all ready to go. I would move these issues over to feather-ui but I don't see a way to do that.

**Comment by richardlayman** [comment]
Latest commit has the ui loaded from a config file - /usr/local/feather/feather.rc. There is only one attribute 'mainpath' which points to the legacy ui, you can change it to point to any qml file you want. Didn't have to put any build flags in this way. If you need any more config options let me know; I went ahead and put in all the parsing code so that it would be easy to parse for more options if needed.

**Comment by mottosso** [comment]
Sounds good, I'll take a look within this week. Thanks @richardlayman, this will be great!

**Comment by mottosso** [comment]
Where did you say you put that config file? Am I meant to create it myself? What format would it be in?

**Comment by richardlayman** [comment]
It's comes with the core. When you install feather it will install feather.rc txt file in /usr/local/feather.

**Comment by mottosso** [comment]
Hm, it isn't showing up for me.

Could you point me to where the behavior for this is located? What decides it should go there, where does this file come from? It isn't even in this repo it seems?

**Comment by richardlayman** [comment]
You might have to re-run you cmake or verify that you fetched the right commit. The file is here
https://github.com/feather3d/feather/commit/8a5c8b7b167919c33cfe619dae40b1763a4d7cfc
And cmake is setup correctly. I've also tested it several times and it working fine.
